from readModelInputs import contractorsList, totalDemands, demandsAfterBaseConservation, finalSuppliesDf, finalDemandsAfterBaseConservationDf
from modelUtilities import subtractSuppliesByPriority


for contractor in contractorsList:
    for i in range(len(historicHydrologyYears)):


#Subtracting Supply Priority
finaldemandsAfterPriority1SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finalDemandsAfterBaseConservationDf, 1)
finaldemandsAfterPriority2SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority1SuppliesDf, 2)
finaldemandsAfterPriority3SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority2SuppliesDf, 3)
finaldemandsAfterPriority4SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority3SuppliesDf, 4)
finaldemandsAfterPriority5SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority4SuppliesDf, 5)
finaldemandsAfterPriority6SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority5SuppliesDf, 6)
finaldemandsAfterPriority7SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority6SuppliesDf, 7)
finaldemandsAfterPriority8SuppliesDf = subtractSuppliesByPriority(finalSuppliesDf, finaldemandsAfterPriority7SuppliesDf, 8)